# github api, fetch pr diffs and post review comments

import asyncio
import re
from dataclasses import dataclass

import httpx

API_BASE = "https://api.github.com"
REQUEST_TIMEOUT = 30.0

# transient statuses worth a second try
RETRY_STATUSES = {429, 500, 502, 503, 504}
MAX_RETRIES = 2


async def _with_retry(send):
    # send is a coroutine factory so every attempt is a fresh request.
    # retries transient 5xx and rate limits, honoring retry-after
    resp = await send()
    for _ in range(MAX_RETRIES):
        retryable = resp.status_code in RETRY_STATUSES or (
            resp.status_code == 403 and "rate limit" in resp.text.lower()
        )
        if not retryable:
            return resp
        try:
            delay = min(float(resp.headers.get("retry-after", "")), 30)
        except ValueError:
            delay = 1.0
        await asyncio.sleep(delay)
        resp = await send()
    return resp


# @name not already inside backticks and not part of an email
MENTION_RE = re.compile(r"(?<![`\w])@([A-Za-z0-9-]+)")

GENERATED_FOOTER = "\n\n---\n*Review generated by [PRRev](https://pypi.org/project/prrev/)*"


def _neutralize_mentions(text: str) -> str:
    # backtick @names so posted reviews cant ping people
    return MENTION_RE.sub(r"`@\1`", text)


# matches urls like https://github.com/owner/repo/pull/42.
# owner and repo stick to githubs name charset so a crafted url cant
# steer the api path (dots, encoded slashes etc)
PR_URL_PATTERN = re.compile(r"https://github\.com/([A-Za-z0-9-]+)/([A-Za-z0-9_.-]+)/pull/(\d+)")


@dataclass
class PRInfo:
    owner: str
    repo: str
    number: int
    title: str
    diff: str


def _raise_for_status(resp: httpx.Response) -> None:
    # githubs error body says exactly what was rejected, keep it in the message
    try:
        resp.raise_for_status()
    except httpx.HTTPStatusError as e:
        detail = ""
        try:
            data = resp.json()
            detail = str(data.get("message", ""))
            if data.get("errors"):
                detail += f" {data['errors']}"
        except Exception:
            pass
        if detail.strip():
            raise httpx.HTTPStatusError(
                f"{e} ({detail.strip()})",
                request=e.request,
                response=e.response,
            ) from None
        raise


def parse_pr_url(url: str) -> tuple[str, str, int]:
    match = PR_URL_PATTERN.match(url)
    if not match:
        raise ValueError(f"invalid github PR url: {url}")
    repo = match.group(2)
    # dot-only names are valid for the charset but rewrite the api path
    if repo in {".", ".."}:
        raise ValueError(f"invalid github PR url: {url}")
    return match.group(1), repo, int(match.group(3))


async def fetch_pr(owner: str, repo: str, number: int, token: str) -> PRInfo:
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
    }

    async with httpx.AsyncClient(
        base_url=API_BASE,
        headers=headers,
        follow_redirects=True,
        timeout=REQUEST_TIMEOUT,
    ) as client:
        # metadata and the diff (via the diff accept header) are independent,
        # fetch both at once
        resp, diff_resp = await asyncio.gather(
            _with_retry(lambda: client.get(f"/repos/{owner}/{repo}/pulls/{number}")),
            _with_retry(
                lambda: client.get(
                    f"/repos/{owner}/{repo}/pulls/{number}",
                    headers={"Accept": "application/vnd.github.v3.diff"},
                )
            ),
        )
        _raise_for_status(resp)
        _raise_for_status(diff_resp)
        pr_data = resp.json()

    return PRInfo(
        owner=owner,
        repo=repo,
        number=number,
        title=pr_data.get("title", ""),
        diff=diff_resp.text,
    )


async def post_review(
    owner: str,
    repo: str,
    number: int,
    body: str,
    token: str,
    items: list[dict] | None = None,
) -> None:
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
    }

    # review text comes from the llm, keep it from pinging people
    body = _neutralize_mentions(body)

    # build inline comments from items that have file + line
    comments = []
    if items:
        for item in items:
            if item.get("file") and item.get("line"):
                comments.append(
                    {
                        "path": item["file"],
                        "line": item["line"],
                        "side": item.get("side", "RIGHT"),
                        "body": _neutralize_mentions(
                            f"**{item['severity'].upper()}**: "
                            f"{item['summary']}\n\n{item['explanation']}"
                        ),
                    }
                )

    payload: dict = {
        "body": body + GENERATED_FOOTER,
        "event": "COMMENT",
    }
    if comments:
        payload["comments"] = comments

    async with httpx.AsyncClient(
        base_url=API_BASE,
        headers=headers,
        follow_redirects=True,
        timeout=REQUEST_TIMEOUT,
    ) as client:
        resp = await _with_retry(
            lambda: client.post(
                f"/repos/{owner}/{repo}/pulls/{number}/reviews",
                json=payload,
            )
        )

        # github rejects the whole review if any inline comment targets a
        # line thats not in the diff. fall back to posting everything in
        # the body so the review still goes through
        if resp.status_code == 422 and comments:
            fallback_lines = [body, "\n---\n"]
            for c in comments:
                fallback_lines.append(f"**{c['path']}:{c['line']}** — {c['body']}\n")
            payload = {
                "body": "\n".join(fallback_lines) + GENERATED_FOOTER,
                "event": "COMMENT",
            }
            resp = await _with_retry(
                lambda: client.post(
                    f"/repos/{owner}/{repo}/pulls/{number}/reviews",
                    json=payload,
                )
            )

        _raise_for_status(resp)
